name: cson-forge
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - PyCO2SYS
  - black
  - cartopy
  - cmocean
  - compilers
  - copernicusmarine
  - coverage
  - dask
  - dask-jobqueue
  - distributed
  - esmpy
  - ffmpeg
  - flake8
  - h5py
  - holoviews
  - ipykernel
  - ipywidgets
  - gdown
  - jupyterlab
  - jupyter-book
  - mamba
  - matplotlib
  - mpich
  - nc-time-axis
  - netCDF4
  - netcdf-fortran
  - numpy>2,<2.3
  - pandas
  - papermill
  - pip    
  - pop-tools
  - pre-commit==3.8.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - pytest-xdist>=3.0.0
  - pyyaml>=6.0
  - rasterio
  - rioxarray
  - roms-tools==3.3.0
  - scipy
  - seawater
  - xarray
  - xesmf
  - xgcm
  - zarr
  - pip:
    - -e .
