name: cson-forge-v0
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - PyCO2SYS
  - black
  - cartopy
  - cmocean
  - copernicusmarine
  - coverage
  - dask
  - dask-jobqueue
  - distributed
  - ffmpeg
  - flake8
  - h5py
  - holoviews
  - ipykernel
  - ipywidgets
  - gdown
  - jupyterlab
  - jupyter-book
  - matplotlib
  - nc-time-axis
  - netCDF4
  - numpy>2,<2.3
  - pandas
  - papermill
  - pip    
  - pop-tools
  - pre-commit==3.8.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - pytest-xdist>=3.0.0
  - pyyaml>=6.0
  - rasterio
  - rioxarray
  - scipy
  - seawater
  - xarray
  - zarr
  - pip:
    # roms-tools from GitHub: use branch (e.g. @main) or commit hash (e.g. @abc123f)
    - git+https://github.com/CWorthy-ocean/roms-tools.git@40b5a2ea326dc08a98ac227520e52b13aa24f615
    # cstar-ocean from GitHub: use branch (e.g. @main) or commit hash (e.g. @abc123f)    
    #- git+https://github.com/CWorthy-ocean/C-Star.git@04ed63ca499a537e96749150882abebf195298b0
    - git+https://github.com/matt-long/C-Star.git@f56f115
 
  - xarray>=2022.6.0,<2025.8.0
  - pooch
  - packaging
  - gcm_filters >=0.5.1
  - netcdf4
  - PyYAML
  - pyamg
  - bottleneck
  - regionmask
  - xgcm>=0.9.0
  - numba>=0.61.2
  - pydantic>2,<3
  - dask[diagnostics]
  - gcsfs
