name: cson-forge-v0
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - PyCO2SYS
  - black
  - cartopy
  - cmocean
  - copernicusmarine
  - coverage
  - dask
  - dask-jobqueue
  - distributed
  - ffmpeg
  - flake8
  - h5py
  - holoviews
  - ipykernel
  - ipywidgets
  - gdown
  - jupyterlab
  - jupyter-book
  - matplotlib
  - nc-time-axis
  - netCDF4
  - numpy>2,<2.3
  - pandas
  - papermill
  - pip    
  - pop-tools
  - pre-commit==3.8.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - pytest-xdist>=3.0.0
  - pyyaml>=6.0
  - rasterio
  - rioxarray
  - scipy
  - seawater
  - xarray
  - xgcm
  - zarr
  - pip:
    # roms-tools from GitHub: use branch (e.g. @main) or commit hash (e.g. @abc123f)
    - git+https://github.com/CWorthy-ocean/roms-tools.git@02d3b25
    # cstar-ocean from GitHub: use branch (e.g. @main) or commit hash (e.g. @abc123f)    
    - git+https://github.com/matt-long/C-Star.git@90af620
