name: cson_roms-marbl_v0.1_ccs-12km_1232procs
description: California Current System
application: roms_marbl
state: notset
valid_start_date: '2024-01-01T00:00:00'
valid_end_date: '2024-01-02T00:00:00'
code:
  roms:
    documentation: ''
    locked: false
    location: https://github.com/CWorthy-ocean/ucla-roms.git
    commit: 84f4ee7886e9ee4c33b3248b35c955551f3b9c06
    branch: ''
    filter: null
  run_time:
    documentation: ''
    locked: false
    location: placeholder://run_time
    commit: ''
    branch: main
    filter: null
  compile_time:
    documentation: ''
    locked: false
    location: placeholder://compile_time
    commit: ''
    branch: main
    filter: null
  marbl:
    documentation: ''
    locked: false
    location: https://github.com/marbl-ecosys/MARBL.git
    commit: marbl0.45.0
    branch: ''
    filter: null
initial_conditions:
  documentation: ''
  locked: false
  data:
  - location: /anvil/projects/x-ees250129/cson-forge-data/x-mlong/input-data/cson_roms-marbl_v0.1_ccs-12km_1232procs/cson_roms-marbl_v0.1_ccs-12km_1232procs_initial_conditions.nc
    partitioned: false
grid:
  documentation: ''
  locked: false
  data:
  - location: /anvil/projects/x-ees250129/cson-forge-data/x-mlong/input-data/cson_roms-marbl_v0.1_ccs-12km_1232procs/cson_roms-marbl_v0.1_ccs-12km_1232procs_grid.nc
    partitioned: false
forcing:
  boundary:
    documentation: ''
    locked: false
    data:
    - location: /anvil/projects/x-ees250129/cson-forge-data/x-mlong/input-data/cson_roms-marbl_v0.1_ccs-12km_1232procs/cson_roms-marbl_v0.1_ccs-12km_1232procs_boundary-physics_202401.nc
      partitioned: false
    - location: /anvil/projects/x-ees250129/cson-forge-data/x-mlong/input-data/cson_roms-marbl_v0.1_ccs-12km_1232procs/cson_roms-marbl_v0.1_ccs-12km_1232procs_boundary-bgc_clim.nc
      partitioned: false
  surface:
    documentation: ''
    locked: false
    data:
    - location: /anvil/projects/x-ees250129/cson-forge-data/x-mlong/input-data/cson_roms-marbl_v0.1_ccs-12km_1232procs/cson_roms-marbl_v0.1_ccs-12km_1232procs_surface-physics_202401.nc
      partitioned: false
    - location: /anvil/projects/x-ees250129/cson-forge-data/x-mlong/input-data/cson_roms-marbl_v0.1_ccs-12km_1232procs/cson_roms-marbl_v0.1_ccs-12km_1232procs_surface-bgc_clim.nc
      partitioned: false
  tidal:
    documentation: ''
    locked: false
    data:
    - location: /anvil/projects/x-ees250129/cson-forge-data/x-mlong/input-data/cson_roms-marbl_v0.1_ccs-12km_1232procs/cson_roms-marbl_v0.1_ccs-12km_1232procs_tidal.nc
      partitioned: false
  river:
    documentation: ''
    locked: false
    data:
    - location: /anvil/projects/x-ees250129/cson-forge-data/x-mlong/input-data/cson_roms-marbl_v0.1_ccs-12km_1232procs/cson_roms-marbl_v0.1_ccs-12km_1232procs_river.nc
      partitioned: false
  corrections: null
partitioning:
  documentation: ''
  locked: false
  hash: null
  n_procs_x: 28
  n_procs_y: 44
