name: cson_roms-marbl_v0.1_ccs-12km
description: California Current System
application: roms_marbl
state: notset
valid_start_date: '2024-01-01T00:00:00'
valid_end_date: '2024-01-02T00:00:00'
code:
  roms:
    documentation: ''
    locked: false
    location: https://github.com/CWorthy-ocean/ucla-roms.git
    commit: ''
    branch: main
    filter: null
  run_time:
    documentation: ''
    locked: false
    location: placeholder://run_time
    commit: ''
    branch: main
    filter: null
  compile_time:
    documentation: ''
    locked: false
    location: placeholder://compile_time
    commit: ''
    branch: main
    filter: null
  marbl:
    documentation: ''
    locked: false
    location: https://github.com/marbl-ecosys/MARBL.git
    commit: marbl0.45.0
    branch: ''
    filter: null
initial_conditions:
  documentation: ''
  locked: false
  data:
  - location: /Users/mclong/cson-forge-data/input-data/cson_roms-marbl_v0.1_ccs-12km/cson_roms-marbl_v0.1_initial_conditions.nc
    partitioned: false
grid:
  documentation: ''
  locked: false
  data:
  - location: /Users/mclong/cson-forge-data/input-data/cson_roms-marbl_v0.1_ccs-12km/cson_roms-marbl_v0.1_grid.nc
    partitioned: false
forcing:
  boundary:
    documentation: ''
    locked: false
    data:
    - location: /Users/mclong/cson-forge-data/input-data/cson_roms-marbl_v0.1_ccs-12km/cson_roms-marbl_v0.1_boundary-physics_202401.nc
      partitioned: false
    - location: /Users/mclong/cson-forge-data/input-data/cson_roms-marbl_v0.1_ccs-12km/cson_roms-marbl_v0.1_boundary-bgc_clim.nc
      partitioned: false
  surface:
    documentation: ''
    locked: false
    data:
    - location: /Users/mclong/cson-forge-data/input-data/cson_roms-marbl_v0.1_ccs-12km/cson_roms-marbl_v0.1_surface-physics_202401.nc
      partitioned: false
    - location: /Users/mclong/cson-forge-data/input-data/cson_roms-marbl_v0.1_ccs-12km/cson_roms-marbl_v0.1_surface-bgc_clim.nc
      partitioned: false
  tidal:
    documentation: ''
    locked: false
    data:
    - location: /Users/mclong/cson-forge-data/input-data/cson_roms-marbl_v0.1_ccs-12km/cson_roms-marbl_v0.1_tidal.nc
      partitioned: false
  river:
    documentation: ''
    locked: false
    data:
    - location: /Users/mclong/cson-forge-data/input-data/cson_roms-marbl_v0.1_ccs-12km/cson_roms-marbl_v0.1_river.nc
      partitioned: false
  corrections: null
partitioning:
  documentation: ''
  locked: false
  hash: null
  n_procs_x: 16
  n_procs_y: 20
