name: cson_roms-marbl_v0.1_test-tiny
description: Test tiny
application: roms_marbl
state: notset
valid_start_date: '2012-01-01T00:00:00'
valid_end_date: '2012-01-02T00:00:00'
code:
  roms:
    documentation: ''
    locked: false
    location: https://github.com/CWorthy-ocean/ucla-roms.git
    commit: ''
    branch: main
  run_time:
    documentation: ''
    locked: false
    location: placeholder://run_time
    commit: ''
    branch: main
  compile_time:
    documentation: ''
    locked: false
    location: placeholder://compile_time
    commit: ''
    branch: main
  marbl:
    documentation: ''
    locked: false
    location: https://github.com/marbl-ecosys/MARBL.git
    commit: marbl0.45.0
    branch: ''
initial_conditions:
  documentation: ''
  locked: false
  data:
  - partitioned: false
grid:
  documentation: ''
  locked: false
  data:
  - partitioned: false
forcing:
  boundary:
    documentation: ''
    locked: false
    data:
    - partitioned: false
  surface:
    documentation: ''
    locked: false
    data:
    - partitioned: false
partitioning:
  documentation: ''
  locked: false
  n_procs_x: 2
  n_procs_y: 1
